<?php

return [
    'employee_type' => [
        '' => '',
        'employee' => 'employee',
        'contractor' => 'contractor',
    ],
    'loe_type' => [
        'Consultant'=>'Consultant',
        'Senior Consultant'=>'Senior Consultant',
        'Managing Consultant'=>'Managing Consultant',
        'Managing Business Consultant'=>'Managing Business Consultant'
    ],
    'region' => [
        '' => '',
        'Europe' => 'Europe',
        'MEA' => 'MEA',
        'NAM' => 'NAM',
        'LATAM' => 'LATAM',
        'APAC' => 'APAC',
        'Russia' => 'Russia',
    ],
    'job_role' => [
        '' => '',
        'ASC' => 'ASC',
        'ISC' => 'ISC',
    ],
    'domain-users' => [
        '' => '',
        'APM' => 'APM',
        'Security' => 'Security',
        'SDLAN' => 'SDLAN',
        'SDWAN' => 'SDWAN',
        'UC' => 'UC',
        'CC' => 'CC',
        'SMS' => 'SMS',
        'DD' => 'DD',
    ],
    'domain-projects' => [
        'Hybrid Security' => 'Hybrid Security',
        'Hybrid APM' => 'Hybrid APM',
        'Hybrid Network' => 'Hybrid Network',
        'UC' => 'UC',
    ],
    'meta_activity' => [
        'BILLABLE' => 'BILLABLE',
        'ABS' => 'ABS',
        'OTHER' => 'OTHER',
        'CF' => 'CF',
    ],
    'project_status' => [
        'Pipeline' => 'Pipeline',
        'Started' => 'Started',
        'Closed' => 'Closed',
    ],
    'project_type' => [
        'Baseline' => 'Baseline',
        'Project' => 'Project',
        'Pre-sales' => 'Pre-sales',
        'Orange absence or other' => 'Orange absence or other',
    ],
    'project_subtype' => [
        'POC' => 'POC',
        'Assessment' => 'Assessment',
        'Pilot' => 'Pilot',
        'Build/Run' => 'Build/Run',
        'Recurring consulting' => 'Recurring consulting',
        'OpenLab' => 'OpenLab',
    ],
    'samba_stage' => [
        '1 Pre-Qualification' => '1 Pre-Qualification',
        '2 Qualification' => '2 Qualification',
        '3 Proposal' => '3 Proposal',
        '4 Negotiation' => '4 Negotiation',
        '5 Handover' => '5 Handover',
        'Closed Cancelled' => 'Closed Cancelled',
        'Closed Duplicate' => 'Closed Duplicate',
        'Closed Lost' => 'Closed Lost',
        'Closed Won' => 'Closed Won',
    ],
    'activity_type' => [
        '' => '',
        'ISC' => 'ISC',
        'ASC' => 'ASC',
    ],
    'year' => [
        '2017' => '2017',
        '2018' => '2018',
        '2019' => '2019',
        '2020' => '2020',
        '2021' => '2021',
        '2022' => '2022',
        '2023' => '2023',
        '2024' => '2024',
        '2025' => '2025',
    ],
    'week' => [
        '1' => 'Week 01',
        '2' => 'Week 02',
        '3' => 'Week 03',
        '4' => 'Week 04',
        '5' => 'Week 05',
        '6' => 'Week 06',
        '7' => 'Week 07',
        '8' => 'Week 08',
        '9' => 'Week 09',
        '10' => 'Week 10',
        '11' => 'Week 11',
        '12' => 'Week 12',
        '13' => 'Week 13',
        '14' => 'Week 14',
        '15' => 'Week 15',
        '16' => 'Week 16',
        '17' => 'Week 17',
        '18' => 'Week 18',
        '19' => 'Week 19',
        '20' => 'Week 20',
        '21' => 'Week 21',
        '22' => 'Week 22',
        '23' => 'Week 23',
        '24' => 'Week 24',
        '25' => 'Week 25',
        '26' => 'Week 26',
        '27' => 'Week 27',
        '28' => 'Week 28',
        '29' => 'Week 29',
        '30' => 'Week 30',
        '31' => 'Week 31',
        '32' => 'Week 32',
        '33' => 'Week 33',
        '34' => 'Week 34',
        '35' => 'Week 35',
        '36' => 'Week 36',
        '37' => 'Week 37',
        '38' => 'Week 38',
        '39' => 'Week 39',
        '40' => 'Week 40',
        '41' => 'Week 41',
        '42' => 'Week 42',
        '43' => 'Week 43',
        '44' => 'Week 44',
        '45' => 'Week 45',
        '46' => 'Week 46',
        '47' => 'Week 47',
        '48' => 'Week 48',
        '49' => 'Week 49',
        '50' => 'Week 50',
        '51' => 'Week 51',
        '52' => 'Week 52',
    ],
    'month_names' => [
        '1' => 'Week 01',
        '2' => 'Week 02',
        '3' => 'Week 03',
        '4' => 'Week 04',
        '5' => 'Week 05',
        '6' => 'Week 06',
        '7' => 'Week 07',
        '8' => 'Week 08',
        '9' => 'Week 09',
        '10' => 'Week 10',
        '11' => 'Week 11',
        '12' => 'Week 12',
        '13' => 'Week 13',
        '14' => 'Week 14',
        '15' => 'Week 15',
        '16' => 'Week 16',
        '17' => 'Week 17',
        '18' => 'Week 18',
        '19' => 'Week 19',
        '20' => 'Week 20',
        '21' => 'Week 21',
        '22' => 'Week 22',
        '23' => 'Week 23',
        '24' => 'Week 24',
        '25' => 'Week 25',
        '26' => 'Week 26',
        '27' => 'Week 27',
        '28' => 'Week 28',
        '29' => 'Week 29',
        '30' => 'Week 30',
        '31' => 'Week 31',
        '32' => 'Week 32',
        '33' => 'Week 33',
        '34' => 'Week 34',
        '35' => 'Week 35',
        '36' => 'Week 36',
        '37' => 'Week 37',
        '38' => 'Week 38',
        '39' => 'Week 39',
        '40' => 'Week 40',
        '41' => 'Week 41',
        '42' => 'Week 42',
        '43' => 'Week 43',
        '44' => 'Week 44',
        '45' => 'Week 45',
        '46' => 'Week 46',
        '47' => 'Week 47',
        '48' => 'Week 48',
        '49' => 'Week 49',
        '50' => 'Week 50',
        '51' => 'Week 51',
        '52' => 'Week 52',
        ],
    'available_months' => [
        '1' => 'Week 01',
        '2' => 'Week 02',
        '3' => 'Week 03',
        '4' => 'Week 04',
        '5' => 'Week 05',
        '6' => 'Week 06',
        '7' => 'Week 07',
        '8' => 'Week 08',
        '9' => 'Week 09',
        '10' => 'Week 10',
        '11' => 'Week 11',
        '12' => 'Week 12',
        '13' => 'Week 13',
        '14' => 'Week 14',
        '15' => 'Week 15',
        '16' => 'Week 16',
        '17' => 'Week 17',
        '18' => 'Week 18',
        '19' => 'Week 19',
        '20' => 'Week 20',
        '21' => 'Week 21',
        '22' => 'Week 22',
        '23' => 'Week 23',
        '24' => 'Week 24',
        '25' => 'Week 25',
        '26' => 'Week 26',
        '27' => 'Week 27',
        '28' => 'Week 28',
        '29' => 'Week 29',
        '30' => 'Week 30',
        '31' => 'Week 31',
        '32' => 'Week 32',
        '33' => 'Week 33',
        '34' => 'Week 34',
        '35' => 'Week 35',
        '36' => 'Week 36',
        '37' => 'Week 37',
        '38' => 'Week 38',
        '39' => 'Week 39',
        '40' => 'Week 40',
        '41' => 'Week 41',
        '42' => 'Week 42',
        '43' => 'Week 43',
        '44' => 'Week 44',
        '45' => 'Week 45',
        '46' => 'Week 46',
        '47' => 'Week 47',
        '48' => 'Week 48',
        '49' => 'Week 49',
        '50' => 'Week 50',
        '51' => 'Week 51',
        '52' => 'Week 52',
    ],
    'available_months_h1' => [
        'jan',
        'feb',
        'mar',
        'apr',
        'may',
        'jun',
    ],
    'available_months_h2' => [
        'jul',
        'aug',
        'sep',
        'oct',
        'nov',
        'dec',
    ],
    'userskill_rating' => [
        '1' => '1-basic',
        '2' => '2-proficient',
        '3' => '3-advanced',
        '4' => '4-expert',
    ],
    'usercert_rating' => [
        '1' => 'yes',
    ],
    'defaultRole' => 'User',
    'activity_status' => [
        '' => '',
        'active' => 'active',
        'inact.' => 'inact.',
    ],
    'users-mc' => [
        'DLP30' => 'DLP30',
        'DPS22' => 'DPS22',
        'DMR03' => 'DMR03',
        'DPS26' => 'DPS26',
        'DPS32' => 'DPS32',
        'DPS72' => 'DPS72',
        'DPS52' => 'DPS52',
        'DPS62' => 'DPS62',
        'DPS92' => 'DPS92',
        'DPS42' => 'DPS42',
        'DRU13' => 'DRU13',
        'SRU13' => 'SRU13',
        'DPS37' => 'DPS37',
        'DPS67' => 'DPS67',
        'DPS57' => 'DPS57',
        'DPS27' => 'DPS27',
        'DPS97' => 'DPS97',
        'DPS47' => 'DPS47',
        'DAS58' => 'DAS58',
        'DCB58' => 'DCB58',
        'DCE58' => 'DCE58',
        'DCS58' => 'DCS58',
        'DCV15' => 'DCV15',
        'DCV25' => 'DCV25',
        'DGM58' => 'DGM58',
        'DGS23' => 'DGS23',
        'DGS25' => 'DGS25',
        'DLP30' => 'DGS25',
        'DMR03' => 'DGS25',
        'DMR58' => 'DMR58',
        'DPP20' => 'DMR58',
        'DPS22' => 'DPS22',
        'DPS42' => 'DPS42',
        'DPS52' => 'DPS52',
        'DPS54' => 'DPS52',
        'DRU13' => 'DRU13',
        'DSE01' => 'DRU13',
        'DSP58' => 'DRU13',
        'DSS40' => 'DSS40',
        'DXX33' => 'DXX33',
        'GHG01' => 'GHG01',
        'SCC02' => 'SCC02',
        'SCC03' => 'SCC03',
        'SCC05' => 'SCC05',
        'SGC10' => 'SGC10',
        'SIS10' => 'SIS10',
        'SMR21' => 'SMR21',
        'SPG56' => 'SPG56',
        'SPG64' => 'SPG64',
        'SPS31' => 'SPS31',
        'SPS32' => 'SPS32',
        'SPV02' => 'SPV02',
        'SSM34' => 'SSM34',
        'SPI02' => 'SPI02'
    ],
    'action_status' => [
        'OPEN' => 'OPEN',
        'CLOSED' => 'CLOSED',
        'ON HOLD' => 'ON HOLD',
        'IN IMPLEMENTATION' => 'IN IMPLEMENTATION',
    ],
    'action_severity' => [
        'LOW' => 'LOW',
        'MEDIUM' => 'MEDIUM',
        'TOP' => 'TOP',
    ],
    'loe_stage' => [
        'BUILD' => 'BUILD',
        'RUN' => 'RUN'
    ],

];
